toxic_patterns:
  - name: hex_like
    regex: [0-9a-fA-F]{16,} # Matches long sequences of hex characters
    confidence_weight: 0.8
  - name: base64_like
    regex: [A-Za-z0-9+/=]{24,} # Matches long sequences of base64 characters
    confidence_weight: 0.9
  - name: ip_address
    regex: (?:[0-9]{1,3}\\.){3}[0-9]{1,3} # Matches IPv4 addresses
    confidence_weight: 0.6
  - name: email_address
    regex: [a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.com # Matches common email patterns
    confidence_weight: 0.7

# Configuration for entropy-based detection
entropy_threshold: 4.0 # Example threshold for high entropy (e.g., random strings)

# Configuration for ML-based detection
ml_model_path: models/toxic_gate_lr_v1.joblib


