name: C9.3 Anonymization CI
on:
  push:
    branches: [ main, master, develop ]
    paths:
      - "scripts/**"
      - "tests/**"
      - "docs/**"
      - ".github/workflows/c9_3-anonymizer-ci.yml"
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  test-anonymizer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run unit tests
        run: pytest -q

      - name: Smoke test (CLI)
        run: python3 scripts/validate_anonymizer.py

      - name: Install jq for JSON checks
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Create a tiny sample ledger (JSON Lines)
        run: |
          mkdir -p ci_artifacts
          cat > ci_artifacts/sample_ledger.jsonl <<'JL'
{"source_id":"alpha","value":1}
{"source_id":"beta","value":2}
{"source_id":"alpha","value":3}
JL

      - name: Run batch anonymization with ephemeral salt
        env:
          HEART_PROTOCOL_SALT: "ci_ephemeral_salt_42"
        run: |
          ./scripts/run_anonymization.sh ci_artifacts/sample_ledger.jsonl ci_artifacts/sample_ledger_anonymized.jsonl
          echo "---- PREVIEW ----"
          head -n 3 ci_artifacts/sample_ledger_anonymized.jsonl

      - name: Verify anonymized output shape
        run: |
          test $(wc -l < ci_artifacts/sample_ledger_anonymized.jsonl) -eq 3
          # Ensure no 'source_id' remains and 'anonymous_id' exists on each line
          ! grep -q '"source_id"' ci_artifacts/sample_ledger_anonymized.jsonl
          awk 'NR==1{print}{next}' ci_artifacts/sample_ledger_anonymized.jsonl | while IFS= read -r line; do
            echo "$line" | jq -e 'has("anonymous_id")' > /dev/null
          done
          # Determinism check: lines 1 and 3 had the same source_id ("alpha"); hashes must match
          h1=$(sed -n '1p' ci_artifacts/sample_ledger_anonymized.jsonl | jq -r '.anonymous_id')
          h3=$(sed -n '3p' ci_artifacts/sample_ledger_anonymized.jsonl | jq -r '.anonymous_id')
          test "$h1" = "$h3"

      - name: Upload anonymized sample as artifact
        uses: actions/upload-artifact@v4
        with:
          name: c9_3-anonymized-sample
          path: ci_artifacts/sample_ledger_anonymized.jsonl
