name: Ghost Guard

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  ghost-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev] jsonschema
      - name: Run ghost scanner
        run: python tests/ghost_scanner.py
