name: Main CI

on:
  push:
    branches: [main, dev, sprint/*]
  pull_request:

jobs:
  ghost-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest jsonschema pyyaml

      - name: Ghost Scanner
        run: python tests/ghost_scanner.py

      - name: Salt presence check
        run: |
          if [[ -z "${{ secrets.HEART_PROTOCOL_SALT }}" ]]; then
            echo "::error::HEART_PROTOCOL_SALT secret missing"; exit 2
          fi

      - name: Run unit tests
        run: pytest -q
        env:
          HEART_PROTOCOL_SALT: ${{ secrets.HEART_PROTOCOL_SALT }}
