name: Main CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: ''

      - name: Set witness
        run: echo "WITNESS=${{ github.sha }}" >> $GITHUB_ENV

      - name: Check HEART_PROTOCOL_SALT (warn)
        run: |
          if [ -z "${{ secrets.HEART_PROTOCOL_SALT }}" ]; then
            echo "::warning::HEART_PROTOCOL_SALT not set. CI will proceed using test salt if needed."
          fi

      - name: NUKE - Clean workspace before install
        run: |
          echo "Nuking all build artifacts and ghost directories..."
          find . -type d -name "*.egg-info" -exec rm -rf {} +
          find . -type d -name "__pycache__" -exec rm -rf {} +
          rm -rf build/ dist/
          echo "Nuke complete. Workspace is clean."

      - name: Install project (with dev dependencies)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir -e .[dev]

      - name: Run tests
        env:
          HEART_PROTOCOL_SALT: ${{ secrets.HEART_PROTOCOL_SALT }}
        run: |
          pytest -q
