name: Main CI

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Set witness
        run: echo "WITNESS=facfbc1" >> $GITHUB_ENV

      - name: Check HEART_PROTOCOL_SALT (warn)
        run: |
          if [ -z "${{ secrets.HEART_PROTOCOL_SALT }}" ]; then
            echo "::warning::HEART_PROTOCOL_SALT not set. CI will proceed using test salt if needed."
          fi

      - name: Install project (pyproject or setup.py)
        run: |
          python -m pip install --upgrade pip
          if [ -f "pyproject.toml" ]; then
            pip install -e .[dev] || pip install -e .
          elif [ -f "setup.py" ]; then
            pip install -e .
          else
            echo "No pyproject.toml or setup.py found; skipping project install step."
          fi

      - name: Run tests
        env:
          HEART_PROTOCOL_SALT: ${{ secrets.HEART_PROTOCOL_SALT }}
        run: |
          pytest

      - name: Run Resonance Metric (example)
        run: |
          python -m metrics.resonance_metric --input samples --output-json resonance_output.json

      - name: Upload Resonance Report
        uses: actions/upload-artifact@v4
        with:
          name: resonance-report
          path: resonance_output.json

