name: Secret Check

on: [push, pull_request]

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Verify HEART_PROTOCOL_SALT secret
        run: |
          if [ -z "${{ secrets.HEART_PROTOCOL_SALT }}" ]; then
            echo "::error::HEART_PROTOCOL_SALT secret missing"
            exit 1
          else
            echo "HEART_PROTOCOL_SALT is set"
          fi
