name: Immortal Witness
on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Snapshot and publish
        run: |
          python3 scripts/witness_snapshot.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: witness-snapshot
          path: ci_artifacts/witness_snapshot.json
